# Generate a Random String for Uniqueness
resource "random_string" "random" {
  length  = 6
  special = false
  upper   = false
}


module "azapiidentity" {
  source  = "Azure/avm-res-managedidentity-userassignedidentity/azurerm"
  version = "0.3.4"

  enable_telemetry = false

  resource_group_name = module.resource_group.monitoring.name
  location            = module.resource_group.monitoring.resource.location
  name                = "azapi-identity"
}

# Function Plan (Flex Consumption)
resource "azapi_resource" "serverFarm" {
  type                      = "Microsoft.Web/serverfarms@2023-12-01"
  schema_validation_enabled = true
  location                  = module.resource_group.monitoring.resource.location
  name                      = "plan-func-${random_string.random.result}-azapi"
  parent_id                 = module.resource_group.monitoring.resource_id
  ignore_casing             = false
  ignore_missing_property   = true
  body = {
    kind = "functionapp",
    sku = {
      capacity = 0
      family   = "FC"
      name     = "FC1"
      size     = "FC1"
      tier     = "FlexConsumption"
    }
    properties = {
      elasticScaleEnabled       = false
      freeOfferExpirationTime   = null
      hostingEnvironmentProfile = null
      hyperV                    = false
      isSpot                    = false
      isXenon                   = false
      kubeEnvironmentProfile    = null
      maximumElasticWorkerCount = 1
      perSiteScaling            = false
      reserved                  = true
      spotExpirationTime        = null
      targetWorkerCount         = 0
      targetWorkerSizeId        = 0
      workerTierName            = null
      zoneRedundant             = false
    }
  }
}


# Function App Deployment
# resource "azapi_resource" "functionApps" {
#   type = "Microsoft.Web/sites@2024-04-01"
#   schema_validation_enabled = false
#   location = module.resource_group.monitoring.resource.location
#   name = "func-${local.uniquekey}-${random_string.random.result}-azapi"
#   parent_id = module.resource_group.monitoring.resource_id
#   body = {
#     kind = "functionapp,linux",
#     identity = {
#       type = "SystemAssigned"
#     }
#     properties = {
#       serverFarmId = azapi_resource.serverFarm.id,
#       functionAppConfig = {
#         deployment = {
#           storage = {
#             type = "blobcontainer",
#             value = "https://${module.storage_account.tfazapi.fqdn.blob}/monitoring"
#             authentication = {
#               type = "systemassignedidentity"
#             }
#           }
#         },
#         scaleAndConcurrency = {
#           maximumInstanceCount = 100,
#           instanceMemoryMB = 2048
#         },
#         runtime = { 
#           name = "python" 
#           version = "3.11"
#         }
#       }
#     }
#   }
# }


resource "azapi_resource" "functionApps" {
  type                      = "Microsoft.Web/sites@2024-04-01"
  schema_validation_enabled = false
  ignore_casing             = false
  ignore_missing_property   = true
  location                  = module.resource_group.monitoring.resource.location
  name                      = "func-${local.uniquekey}-${random_string.random.result}-azapi"
  parent_id                 = module.resource_group.monitoring.resource_id


  body = {
    kind = "functionapp,linux"
    # !!! Does not work !!!
    # identity = {
    #   userAssignedIdentities = [ module.azapiidentity.resource_id ]
    #   type         = "UserAssigned"
    # }
    identity = {
      type = "SystemAssigned"
    }
    properties = {
      autoGeneratedDomainNameLabelScope = null
      clientAffinityEnabled             = false
      clientCertEnabled                 = false
      clientCertExclusionPaths          = null
      clientCertMode                    = "Required"
      cloningInfo                       = null
      containerSize                     = 1536
      customDomainVerificationId        = "DB3BC7C3AF991E4C9D85C8ADF93BF175A8126D148C2097F619C7FD10E11AA5E1"
      dailyMemoryTimeQuota              = 0
      daprConfig                        = null
      dnsConfiguration                  = {}
      enabled                           = true
      endToEndEncryptionEnabled         = false
      functionAppConfig = {
        deployment = {
          storage = {
            authentication = {
              storageAccountConnectionStringName = null
              type                               = "systemassignedidentity"
              # type                               = "userassignedidentity"
              # userAssignedIdentityResourceId     = module.azapiidentity.resource_id
            }
            type  = "blobcontainer"
            value = "https://${module.storage_account.tfazapi.fqdn.blob}/monitoring"
          }
        }
        runtime = {
          name    = "python"
          version = "3.11"
        }
        scaleAndConcurrency = {
          alwaysReady          = null
          instanceMemoryMB     = 2048
          maximumInstanceCount = 100
          triggers             = null
        }
      }
      hostNameSslStates = [{
        hostType   = "Standard"
        name       = "func-${local.uniquekey}-${random_string.random.result}-azapi.azurewebsites.net"
        sslState   = "Disabled"
        thumbprint = null
        toUpdate   = null
        virtualIP  = null
        }, {
        hostType   = "Repository"
        name       = "func-${local.uniquekey}-${random_string.random.result}-azapi.scm.azurewebsites.net"
        sslState   = "Disabled"
        thumbprint = null
        toUpdate   = null
        virtualIP  = null
      }]
      hostNamesDisabled         = false
      hostingEnvironmentProfile = null
      httpsOnly                 = true
      hyperV                    = false
      ipMode                    = "IPv4"
      isXenon                   = false
      keyVaultReferenceIdentity = "SystemAssigned"
      managedEnvironmentId      = null
      publicNetworkAccess       = "Enabled"
      redundancyMode            = "None"
      reserved                  = true
      resourceConfig            = null
      scmSiteAlsoStopped        = false
      serverFarmId              = azapi_resource.serverFarm.id
      siteConfig = {
        acrUseManagedIdentityCreds = false
        acrUserManagedIdentityID   = null
        alwaysOn                   = false
        apiDefinition              = null
        apiManagementConfig        = null
        appCommandLine             = null
        appSettings = [
          {
            name  = "AzureWebJobsStorage__blobServiceUri"
            value = "https://${module.storage_account.tfazapi.resource.name}.blob.core.windows.net"
          },
          {
            name  = "AzureWebJobsStorage__queueServiceUri"
            value = "https://${module.storage_account.tfazapi.resource.name}.queue.core.windows.net"
          },
          {
            name  = "AzureWebJobsStorage__tableServiceUri"
            value = "https://${module.storage_account.tfazapi.resource.name}.table.core.windows.net"
          },
          {
            name : "AzureWebJobsStorage__clientId"
            value : module.azapiidentity.client_id
          },
          {
            name  = "AzureWebJobsStorage__credential"
            value = "azure.identity.DefaultAzureCredential"
          }
        ]
        autoHealEnabled                        = null
        autoHealRules                          = null
        autoSwapSlotName                       = null
        azureStorageAccounts                   = null
        connectionStrings                      = null
        cors                                   = null
        defaultDocuments                       = null
        detailedErrorLoggingEnabled            = null
        documentRoot                           = null
        elasticWebAppScaleLimit                = null
        experiments                            = null
        ftpsState                              = null
        functionAppScaleLimit                  = 100
        functionsRuntimeScaleMonitoringEnabled = null
        handlerMappings                        = null
        healthCheckPath                        = null
        http20Enabled                          = false
        httpLoggingEnabled                     = null
        ipSecurityRestrictions                 = null
        ipSecurityRestrictionsDefaultAction    = null
        javaContainer                          = null
        javaContainerVersion                   = null
        javaVersion                            = null
        keyVaultReferenceIdentity              = null
        limits                                 = null
        linuxFxVersion                         = ""
        loadBalancing                          = null
        localMySqlEnabled                      = null
        logsDirectorySizeLimit                 = null
        managedPipelineMode                    = null
        managedServiceIdentityId               = null
        metadata                               = null
        minTlsCipherSuite                      = null
        minTlsVersion                          = null
        minimumElasticInstanceCount            = 0
        netFrameworkVersion                    = null
        nodeVersion                            = null
        numberOfWorkers                        = 1
        phpVersion                             = null
        powerShellVersion                      = null
        preWarmedInstanceCount                 = null
        publicNetworkAccess                    = null
        publishingUsername                     = null
        push                                   = null
        pythonVersion                          = null
        remoteDebuggingEnabled                 = null
        remoteDebuggingVersion                 = null
        requestTracingEnabled                  = null
        scmIpSecurityRestrictions              = null
        scmIpSecurityRestrictionsDefaultAction = null
        scmIpSecurityRestrictionsUseMain       = null
        scmMinTlsVersion                       = null
        scmType                                = null
        tracingOptions                         = null
        use32BitWorkerProcess                  = null
        virtualApplications                    = null
        vnetName                               = null
        vnetPrivatePortsCount                  = null
        vnetRouteAllEnabled                    = null
        webSocketsEnabled                      = null
        websiteTimeZone                        = null
        windowsFxVersion                       = null
        xManagedServiceIdentityId              = null
      }
      storageAccountRequired   = false
      virtualNetworkSubnetId   = null
      vnetBackupRestoreEnabled = false
      vnetContentShareEnabled  = false
      vnetImagePullEnabled     = false
      vnetRouteAllEnabled      = false
      workloadProfileName      = null
    }
  }
}
